all:
  hosts:
    worker1:
      mac: "11:22:33:44:55:66"
      hostname: "worker-1"
      network:
        - interface: eno1
          addresses:
            - 192.168.1.203/24
      vlans:
        - id: 10
          link: eno1
          addresses:
            - 10.6.3.203/24
    worker2:
      mac: "12:22:33:44:55:66"
      hostname: "worker-2"
      network:
        - interface: eno1
          addresses:
            - 192.168.1.202/24
      vlans:
        - id: 10
          link: eno1
          addresses:
            - 10.6.3.202/24

  children:
    metal:
      hosts:
        worker1:
      vars:
        storage:
          config:
          - {grub_device: false, id: "main-disk", name: '', path: "{{ disk_device }}", preserve: false,
              ptable: gpt, type: disk, wipe: superblock-recursive}

          # Partition 1 /boot/efi
          - {device: "main-disk", flag: boot, grub_device: true, id: partition-1, number: 1,
              preserve: false, size: "512M", type: partition, wipe: superblock}
          - {fstype: fat32, id: format-1, preserve: false, type: format, volume: partition-1}

          # Partition 2  /boot
          - {device: "main-disk", flag: '', grub_device: false, id: partition-2, number: 2,
              preserve: false, size: "512M", type: partition, wipe: superblock}
          - {fstype: ext4, id: format-2, preserve: false, type: format, volume: partition-2}

          # Partition 3 /
          - {device: "main-disk", flag: '', grub_device: false, id: partition-3, number: 3,
              preserve: false, size: 79G, type: partition, wipe: superblock}
          - {fstype: ext4, id: format-3, preserve: false, type: format, volume: partition-3}

          # For the last partition specified for a particular device, you can specify the size as "-1" to indicate
          # that the partition should fill the remaining space.
          - {device: "main-disk", flag: '', grub_device: false, id: partition-4, number: 4,
              preserve: false, size: -1, type: partition, wipe: superblock}
          # No format in partition-4 we will use as a loopback device
          #- {fstype: ext4, id: format-4, preserve: false, type: format, volume: partition-4}

          # mounts
          - {device: format-3, id: mount-3, path: /, type: mount}
          - {device: format-2, id: mount-2, path: /boot, type: mount}
          - {device: format-1, id: mount-1, path: /boot/efi, type: mount}
          swap:
            size: 0

    ssd500:
      hosts:
          worker1:
      vars:
        disk_device: '/dev/sda'

    nvme500:
      hosts:
          worker2:
      vars:
        disk_device: '/dev/nvme0n1'
