all:
  hosts:
    worker1:
      mac: "11:22:33:44:55:66"
      hostname: "worker1"
      network:
        - interface: eno1
          addresses:
            - 192.168.0.11/24
      vlans:
        - id: 10
          link: eno1
          addresses:
            - 10.6.0.11/24
  children:
    metal:
      hosts:
        worker1:

