
- name: List 'metal' groups config
  ansible.builtin.debug:
    var: groups['metal']

- name: List 'metal' hostvar items config
  ansible.builtin.debug:
    var: hostvars[item].mac
  loop: "{{ groups['metal'] }}"

- name: Download boot image
  ansible.builtin.get_url:
    url: "{{ iso_url }}"
    dest: "{{ role_path }}/files/data/iso/{{ iso_url | basename }}"
    checksum: "{{ iso_checksum }}"
    mode: 0644

- name: Download uefi grub signed
  ansible.builtin.get_url:
    url: "http://archive.ubuntu.com/ubuntu/dists/focal/main/uefi/grub2-amd64/current/grubnetx64.efi.signed"
    dest: "{{ role_path }}/files/data/pxe-config/grubnetx64.efi.signed"
    checksum: "sha256:279a5a755bc248d22799434a261b92698740ab817d8aeccbd0cb7409959a1463"
    mode: 0644

- name: Extract boot image
  ansible.builtin.command:
    cmd: "xorriso -osirrox on -indev
        {{ role_path }}/files/data/iso/{{ iso_url | basename }}
        -extract /
        {{ role_path }}/files/data/os"
    creates: "{{ role_path }}/files/data/os/md5sum.txt"

- name: Generate ks config
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ role_path }}/files/data/ks/{{ item }}"
    mode: 0644
  loop:
    - user-data
    - meta-data
  tags: ["debug"]

- name: Generate ks diretories for custom user-data by mac
  ansible.builtin.file:
    path: "{{ role_path }}/files/data/ks/{{ hostvars[item]['mac'] }}/"
    state: directory
    mode: 0755
  loop: "{{ groups['metal'] }}"
  tags: ["debug"]

- name: Generate ks custom user-data by mac
  ansible.builtin.template:
    src: "user-data.j2"
    dest: "{{ role_path }}/files/data/ks/{{ hostvars[item]['mac'] }}/user-data"
    mode: 0644
  loop: "{{ groups['metal'] }}"
  tags: ["debug"]

- name: Generate ks custom meta-data by mac
  ansible.builtin.template:
    src: "meta-data.j2"
    dest: "{{ role_path }}/files/data/ks/{{ hostvars[item]['mac'] }}/meta-data"
    mode: 0644
  loop: "{{ groups['metal'] }}"
  tags: ["debug"]

- name: Generate pxelinux config
  ansible.builtin.template:
    src: pxelinux.cfg.j2
    dest: "{{ role_path }}/files/data/pxe-config/pxelinux.cfg"
    mode: 0644

- name: Generate DHCP config
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: "{{ role_path }}/files/data/pxe-config/dhcpd.conf"
    mode: 0644

- name: Generate GRUB config
  ansible.builtin.template:
    src: grub.cfg.j2
    dest: "{{ role_path }}/files/data/pxe-config/grub.cfg"
    mode: 0644

- name: Generate grub-custom folder
  ansible.builtin.file:
    path: "{{ role_path }}/files/data/pxe-config/grub-custom/"
    state: directory
    mode: 0755

- name: Generate GRUB 'metal' groups config
  ansible.builtin.template:
    src: grub-mac.cfg.j2
    dest: "{{ role_path }}/files/data/pxe-config/grub-custom/grub-{{ hostvars[item]['mac'] }}.cfg"
    mode: 0644
  loop: "{{ groups['metal'] }}"
  tags: ["debug"]

- name: Generate GRUB groups generic
  ansible.builtin.template:
    src: grub-generic.cfg.j2
    dest: "{{ role_path }}/files/data/pxe-config/grub-custom/grub-generic.cfg"
    mode: 0644
  tags: ["debug"]

- name: Start the ephemeral PXE server
  community.docker.docker_compose:
    project_src: "{{ role_path }}/files"
    state: present
    restarted: true
    build: true

- name: "Check logs with: docker-compose -f {{ role_path }}/files/docker-compose.yml logs -f"
  ansible.builtin.pause:
    prompt: "Ephemeral PXE server running, press enter to stop."

- name: Stop the ephemeral PXE server
  community.docker.docker_compose:
    project_src: "{{ role_path }}/files"
    state: absent

